import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ConfigProviderWrapper from "../components/providers/config-provider";
import "./globals.css";
import axios from "axios";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

axios.defaults.withCredentials = true

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`w-full h-full ${inter.className}`}>
        <ConfigProviderWrapper>{children}</ConfigProviderWrapper>
      </body>
    </html>
  );
}
